project_id = "ocwydrcjrjgroosuzhgs"

[functions.recommend-products]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.suggest-delivery-fee]
verify_jwt = false

[functions.paypal-client-token]
verify_jwt = false

[functions.paypal-create-order]
verify_jwt = false

[functions.paypal-capture-order]
verify_jwt = false
